{
 "title": "FastAPI / Credit Default - Monitoring",
 "tags": [
  "fastapi",
  "prometheus",
  "mlops"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "RPS par handler",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 0, "w": 12, "h": 9 },
   "targets": [
    {
     "expr": "sum by (handler) (rate(http_requests_total{job=\"credit-default-api\"}[1m]))",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "Latency p95 (s)",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 0, "w": 12, "h": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le) (rate(http_request_duration_seconds_bucket{job=\"credit-default-api\"}[5m])))",
     "legendFormat": "p95"
    }
   ]
  },
  {
   "title": "Taux 2xx (%, 5m)",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 9, "w": 8, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(100 * sum(rate(http_requests_total{job=\"credit-default-api\",status=~\"2..\"}[5m])) / clamp_min(sum(rate(http_requests_total{job=\"credit-default-api\"}[5m])), 1e-9)) or on() vector(0)",
     "legendFormat": "2xx ratio"
    }
   ]
  },
  {
   "title": "Taux 4xx (%, 5m)",
   "type": "timeseries",
   "gridPos": { "x": 8, "y": 9, "w": 8, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(100 * sum(rate(http_requests_total{job=\"credit-default-api\",status=~\"4..\"}[5m])) / clamp_min(sum(rate(http_requests_total{job=\"credit-default-api\"}[5m])), 1e-9)) or on() vector(0)",
     "legendFormat": "4xx ratio"
    }
   ]
  },
  {
   "title": "Taux d’erreur 5xx (%, 5m)",
   "type": "timeseries",
   "gridPos": { "x": 16, "y": 9, "w": 8, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(100 * sum(rate(http_requests_total{job=\"credit-default-api\",status=~\"5..\"}[5m])) / clamp_min(sum(rate(http_requests_total{job=\"credit-default-api\"}[5m])), 1e-9)) or on() vector(0)",
     "legendFormat": "5xx ratio"
    }
   ]
  }
 ]
}